media_type: book
name: Book
description: Configuration for book media type

field_extraction_rules:
  - field_name: Title
    field_type: text
    extraction_method: key_concepts
    max_concepts: 5
    weight: 2.0
  
  - field_name: Name
    field_type: text
    extraction_method: key_concepts
    max_concepts: 5
    weight: 2.0
  
  - field_name: Description
    field_type: text
    extraction_method: key_concepts
    max_concepts: 15
    weight: 1.5
  
  - field_name: Summary
    field_type: text
    extraction_method: key_concepts
    max_concepts: 10
    weight: 1.5
  
  - field_name: Author
    field_type: text
    extraction_method: direct_values
    max_concepts: 3
    weight: 2.0
  
  - field_name: Genre
    field_type: list
    extraction_method: direct_values
    max_concepts: 8
    weight: 2.0
  
  - field_name: Keywords
    field_type: list
    extraction_method: direct_values
    max_concepts: 12
    weight: 1.5
  
  - field_name: Publisher
    field_type: text
    extraction_method: direct_values
    max_concepts: 1
    weight: 0.5

plugins_to_run:
  - ConceptExpansionPlugin
  - TemporalAnalysisPlugin

priority_order:
  - Genre
  - Author
  - Title
  - Name
  - Description