FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl

COPY pyproject.toml .
RUN pip install -e .[dev]

COPY src src

CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
