services:
  redis:
    image: redis:7-alpine
    container_name: jellychat_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile.dev
    container_name: jellychat_worker
    depends_on:
      redis:
        condition: service_started
      ollama:
        condition: service_started
      vectordb:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["./docker/worker/entrypoint.sh"]

  ollama:
    image: ollama/ollama
    container_name: jellychat_ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ollama-models:/root/.ollama
    ports:
      - "12434:11434"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12434"]
      interval: 10s
      retries: 5

  vectordb:
    build:
      context: .
      dockerfile: docker/vectordb/Dockerfile
    container_name: jellychat_vectordb
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  ingestor:
    build:
      context: .
      dockerfile: docker/ingestor/Dockerfile.dev
    container_name: jellychat_ingestor
    depends_on:
      redis:
        condition: service_started
      vectordb:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["./docker/ingestor/entrypoint.sh"]

volumes:
  ollama-models:
  qdrant_data:
