# =============================================================================
# Production RAG System - Development Environment (Updated for Redis)
# =============================================================================

networks:
  rag-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
  mongodb-data:
    driver: local
  faiss-data:
    driver: local
  logs-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  # Unified model storage for all NLP models
  model-data:
    driver: local

services:
  # ===========================================================================
  # LLM SERVICES
  # ===========================================================================

  ollama:
    image: ollama/ollama:latest
    container_name: rag-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - model-data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=10m
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - rag-network
    # GPU support - will fail hard if NVIDIA runtime not available
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ===========================================================================
  # DATABASE SERVICES
  # ===========================================================================

  mongodb:
    image: mongo:7.0
    container_name: rag-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=jellyfin_rag
    command: ["mongod", "--quiet"]
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo-express:
    image: mongo-express:latest
    container_name: rag-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH: "false"
    networks:
      - rag-network
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8081"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ===========================================================================
  # REDIS QUEUE SYSTEM
  # ===========================================================================

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    image: jelly-redis
    container_name: rag-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./docker/redis/redis.conf:/etc/redis/redis.conf:ro
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ===========================================================================
  # MICROSERVICES ARCHITECTURE
  # ===========================================================================


  # ===========================================================================
  # SPLIT NLP SERVICES
  # ===========================================================================

  conceptnet-service:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.conceptnet
    image: jelly-conceptnet-service
    container_name: rag-conceptnet-service
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./src:/app/src:ro  # Hot reload
      - ./config:/app/config:ro  # Model configs
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    environment:
      - ENV=docker
      - REDIS_HOST=redis
      - MONGODB_HOST=mongodb
      - LOG_LEVEL=DEBUG
      - ENABLE_METRICS=true
      - ENABLE_CORS=true
    networks:
      - rag-network
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 999
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  gensim-service:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.gensim
    image: jelly-gensim-service
    container_name: rag-gensim-service
    restart: unless-stopped
    ports:
      - "8006:8006"
    volumes:
      - ./src:/app/src:ro  # Hot reload
      - ./config:/app/config:ro  # Model configs
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
      - model-data:/app/models  # Unified model storage
    environment:
      - ENV=docker
      - REDIS_HOST=redis
      - MONGODB_HOST=mongodb
      - LOG_LEVEL=DEBUG
      - GENSIM_DATA_DIR=/app/models/gensim_data
      - ENABLE_METRICS=true
      - ENABLE_CORS=true
    networks:
      - rag-network
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8006/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 999
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  spacy-service:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.spacy
    image: jelly-spacy-service
    container_name: rag-spacy-service
    restart: unless-stopped
    ports:
      - "8007:8007"
    volumes:
      - ./src:/app/src:ro  # Hot reload
      - ./config:/app/config:ro  # Model configs
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
      - model-data:/app/models  # Unified model storage
    environment:
      - ENV=docker
      - REDIS_HOST=redis
      - MONGODB_HOST=mongodb
      - LOG_LEVEL=DEBUG
      - ENABLE_METRICS=true
      - ENABLE_CORS=true
    networks:
      - rag-network
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8007/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 999
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  heideltime-service:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.heideltime
    image: jelly-heideltime-service
    container_name: rag-heideltime-service
    restart: unless-stopped
    ports:
      - "8008:8008"
    volumes:
      - ./src:/app/src:ro  # Hot reload
      - ./config:/app/config:ro  # Model configs
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    environment:
      - ENV=docker
      - REDIS_HOST=redis
      - MONGODB_HOST=mongodb
      - LOG_LEVEL=DEBUG
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      - ENABLE_METRICS=true
      - ENABLE_CORS=true
    networks:
      - rag-network
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 999
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  llm-service:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.llm
    image: jelly-llm-service
    container_name: rag-llm-service
    restart: unless-stopped
    ports:
      - "8002:8002"
    volumes:
      - ./src:/app/src:ro  # Hot reload
      - ./config:/app/config:ro  # Model configs
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    environment:
      - ENV=docker
      - LOG_LEVEL=DEBUG
      - OLLAMA_CHAT_BASE_URL=http://ollama:11434
    networks:
      - rag-network
    depends_on:
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health/ready"]
      interval: 15s
      timeout: 10s
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  model-manager:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.model_manager
    image: jelly-model-manager
    container_name: rag-model-manager
    restart: unless-stopped
    ports:
      - "8005:8005"
    volumes:
      - ./src:/app/src:ro  # Hot reload
      - ./config:/app/config:ro  # Model configs
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
      - model-data:/app/models  # Unified model storage
    environment:
      - ENV=docker
      - LOG_LEVEL=DEBUG
      - REDIS_HOST=redis
      - MONGODB_HOST=mongodb
      - OLLAMA_CHAT_BASE_URL=http://ollama:11434
      - NLTK_DATA=/app/models/nltk_data
      - GENSIM_DATA_DIR=/app/models/gensim_data
      # Service discovery endpoints for microservices
      - CONCEPTNET_SERVICE_URL=http://conceptnet-service:8001
      - GENSIM_SERVICE_URL=http://gensim-service:8006
      - SPACY_SERVICE_URL=http://spacy-service:8007
      - HEIDELTIME_SERVICE_URL=http://heideltime-service:8008
    networks:
      - rag-network
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      llm-service:
        condition: service_healthy
      # Dependencies for microservices
      conceptnet-service:
        condition: service_healthy
      gensim-service:
        condition: service_healthy
      spacy-service:
        condition: service_healthy
      heideltime-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 999
      start_period: 1s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"




  # ===========================================================================
  # RAG SYSTEM SERVICES
  # ===========================================================================

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    image: jelly-api
    container_name: rag-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src:ro  # Hot reload
      - ./config:/app/config:ro  # Media type configs
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    environment:
      - ENV=docker
      - ENABLE_METRICS=true
      - REDIS_HOST=redis
      - MONGODB_HOST=mongodb
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=DEBUG
      - ENABLE_CORS=true
      - ENABLE_API_DOCS=true
      - OLLAMA_CHAT_BASE_URL=http://ollama:11434
      - CONTAINER_TYPE=api
    networks:
      - rag-network
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    image: jelly-worker
    container_name: rag-worker
    restart: unless-stopped
    ports:
      - "8004:8004"  # Metrics endpoint
    volumes:
      - ./src:/app/src:ro  # Hot reload
      - ./config:/app/config:ro  # Plugin routing config
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    environment:
      - ENV=docker
      - REDIS_HOST=redis
      - MONGODB_HOST=mongodb
      - LOG_LEVEL=DEBUG
      - OLLAMA_CHAT_BASE_URL=http://ollama:11434
      - CONTAINER_TYPE=worker
    networks:
      - rag-network
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ===========================================================================
  # MONITORING STACK
  # ===========================================================================

  prometheus:
    image: prom/prometheus:latest
    container_name: rag-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./docker/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=30d'
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: grafana/grafana:latest
    container_name: rag-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./docker/monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./docker/monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_INSTALL_PLUGINS=redis-datasource
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
      - GF_LOG_LEVEL=warn
    networks:
      - rag-network
    depends_on:
      - prometheus
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ===========================================================================
  # WEB SEARCH SERVICE
  # ===========================================================================

  searxng:
    build:
      context: .
      dockerfile: docker/searxng/Dockerfile
    image: jelly-searxng
    container_name: rag-searxng
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./docker/searxng/settings.yml:/etc/searxng/settings.yml:ro
    environment:
      - SEARXNG_SECRET=your-secret-key-change-in-production
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    profiles:
      - search  # Only start with --profile search

  # ===========================================================================
  # FUTURE SERVICES
  # ===========================================================================

  faiss-service:
    build:
      context: .
      dockerfile: docker/faiss/Dockerfile
    image: jelly-faiss
    container_name: rag-faiss-service
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - faiss-data:/app/data
      - ./src:/app/src:ro
      - ./logs:/app/logs
    environment:
      - ENV=docker
      - REDIS_HOST=redis
      - VECTORDB_URL=http://faiss-service:6333
      - LOG_LEVEL=DEBUG
      - FAISS_INDEX_PATH=/app/data/faiss_index
    networks:
      - rag-network
    depends_on:
      redis:
        condition: service_healthy
    profiles:
      - faiss  # Only start with --profile faiss
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
